title: Ben Schneider

email: brs@mit.edu
github_url: https://github.com/joecool
linkedin_url: https://linkedin.com/in/joecool
medium_url: https://medium.com/joecool
twitter_url: https://twitter.com/joecool

exclude: screenshots, LICENSE, README.md
markdown: kramdown

buttons:
 - text: Home
   url: /
 - text: Research
   url: research
 - text: Teaching
   url: teaching
 - text: Publications
   url: publications